-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.5.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-json
        files: \.(bowerrc|jshintrc|json)$
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
        exclude: docs/source/conf.py
        args: ['--max-line-length=82']
    -   id: requirements-txt-fixer
